### ISSUE TITLE
onDestroy-type lifecycle event?

### ISSUE THREAD

**Issue by radicaled** [edvin/tornadofx#120] opened 2016-06-06 07:07 UTC
Is it possible for `FX.replaceComponent` (and any other function that might be called by the framework) to execute an `onDestroy` type method on the `View` and `Fragment` being replaced?

I use RxJava quite a bit, and it keeps a strong reference to its subscriber. Therefore, you have to explicitly unsubscribe from the observer before removing a View / Fragment or else you'll cause a memory leak. When you're manipulating things yourself it's not a problem, since you can notify the views that they need to drop their RxJava subscriptions.

But, if you use the live reload features of tornadofx, you'll start leaking memory again, since it doesn't know anything about any clean-up logic that should be run when a View or Fragment is removed. Having something like an overridable 'onDestroy' on View / Fragment would let you perform the clean-up yourself when the framework calls `FX.replaceComponent` (or etc) for whatever reason.

**Comment by edvin** [comment] 2016-06-06 07:30
I have thought about this myself, good that you bring it up. I'll first check if there is an event on the root node we can subscribe to, for example when it is being disconnected from it's parent or something. If not, we can at least add an overridable method to UIComponent and call it when the framework itself removes the View, and then you can also call this same method manually if needed.

**Comment by edvin** [comment] 2016-06-06 07:36
I could try to add a listener to `root.parentProperty` perhaps.

**Comment by edvin** [comment] 2016-06-06 08:18
I just added `UIComponent.dock` and `UIComponent.undock` - can you check them to see if they can be used to solve your issue?

**Comment by thomasnield** [comment] 2016-06-06 15:01
@radicaled I use RxJava heavily too and own the [RxJavaFX](https://github.com/ReactiveX/RxJavaFX) and [RxKotlinFX](https://github.com/thomasnield/RxKotlinFX) libraries. I never thought of this. On the Rx side I wonder if there are further ways to streamline unsubscription beyond [CompositeBinding](https://github.com/thomasnield/RxKotlinFX#using-and-disposing-compositebinding)...

**Comment by radicaled** [comment] 2016-06-06 15:57
@edvin I'll check it out today and report back! Thanks.

@thomasnield oh, I use both those libraries -- very good! 

For handling subscriptions I'm following some of the patterns of RxSwift (great library), so some of my code looks like this:

```kotlin
// rxName = RxProperty<String>, analogous to RxSwift's "Variable" class
//   it's basically a property backed by BehaviorSubject.
// disposable: object that unsubscribes / cleans up when when dispose() is called
//   can't quite remember why i created it instead of using CompositeSubscription directly...
state.rxName.bindTo(view.rxName).disposeWith(disposable)
// Override that binds an observable's emissions to an ObservableValue 
//   cleans up when done via disposeWith
Observable.timer(1, TimeUnit.SECONDS).map { it.toString() }.bindTo(textProperty()).disposeWith(disposable)
```

The disposable object is cleaned up when views are destroyed. I haven't found a better pattern in RxJava than this at the moment.

**Comment by radicaled** [comment] 2016-06-06 16:30
@edvin works great! The property binding approach is also more future-proof than my current imperative approach, too!

You're doing an amazing job!

**Comment by edvin** [comment] 2016-06-06 17:04
Thanks @radicaled :) I wonder if we should support some kind of disposable registration, so that if you register a disposable, it's dispose() method is called when a view is undocked. Would that be helpful?

**Comment by thomasnield** [comment] 2016-06-06 17:34
@radicaled disposing is something I'm not great at. I'm sure I have a few memory leaks in my apps. Can you show me how your `disposeWith()` extension function is implemented? It might be candidate to include in RxJavaFX and RxKotlinFX...

**Comment by radicaled** [comment] 2016-06-06 18:26
@edvin that would be generally helpful for me, but I don't know how many other people are using the same disposable-type pattern.

@thomasnield https://github.com/thomasnield/RxKotlinFX/issues/7 :)

**Comment by edvin** [comment] 2016-06-06 22:27
Any resource that needs to be released could use this pattern. I'm thinking something like:

```kotlin
val res = MyMemoryHoggingResource()
res.onUndock { dispose() }
```

When the view is undocked, the `dispose()` function on `MyMemoryHoggingResource` would be called. If it doesn't have function called `dispose` but instead let's say a `cleanup()` function, you'd just call that instead:

```kotlin
res.onUndock { cleanup() }
```

But maybe it's not needed now that we have `onUndock`, you'd simply do:

```kotlin
override fun onUndock() {
    res.cleanup()
}
```

**Comment by radicaled** [comment] 2016-06-06 23:47
Feels (to me, at least) that the `onUndock` override captures it pretty well, and would prevent you from accidentally sprinkling `res.onUndock` calls everywhere.

**Comment by edvin** [comment] 2016-06-07 06:19
I agree. OK, we have what we need, so I'll close the issue. Do you have enough to document the feature, @thomasnield ? Please ask if anything is unclear :)

**Closed by edvin** 2016-06-07 06:19 UTC

**Comment by thomasnield** [comment] 2016-06-07 19:44
Let me take a look. I need to round up a lot of miscellaneous utilities like this one and organize them.

**Comment by thomasnield** [comment] 2016-06-07 19:47
Seems pretty clear to me. So the docking functions are on every `Component`? And they fire when they are first created and destroyed respectively?

**Comment by edvin** [comment] 2016-06-08 07:18
For most intents and purposes yes, but to clarify:

- The root node of a View can either be connected to a scene or a parent node. For this description I will refer to that as "parent".

1. When a View's root node is connected to a parent, the `onDock` function is called
2. When a View's root node is disconnected from it's parent, the `onUndock` function is called

Therefore, if you add the View's root node to another parent, the `onDock` function is called. If you later disconnect it and then give it another parent, you will first have a call to `onUndock` followed by another call to `onDock`.

These functions are declared on `UiComponent`, not `Component`, so `Controller` does not have them.

Does that make sense?

**Comment by thomasnield** [comment] 2016-06-13 13:56
I think this is what I've been looking for too. This is probably where you should unsubscribe UI-based RxJava hot Observables to prevent memory leaks.

**Comment by edvin** [comment] 2016-06-13 14:03
Cool! Is there something we can do to make it even smoother to work with RxJava?

**Comment by thomasnield** [comment] 2016-06-13 14:28
If I understand it correctly, nope I think this is great. Quick question though.

Here is a test I did with RxKotlinFX. 

```kotlin
class MyApp: App() {
    override val primaryView = MyView::class
}

class MyView: View() {
    override val root = VBox()

    var requestDialog: Observable<ActionEvent> by singleAssign()

    init {
        with(root) {
            requestDialog = button("Show Dialog").actionEvents()
        }

        requestDialog.subscribe { MyFragment().openModal() }
    }


}

class MyFragment: Fragment() {
    override val root = VBox()
    var buttonClicks: Observable<ActionEvent> by singleAssign()
    var subscription: Subscription by singleAssign()

    init {
        with(root) {
            buttonClicks = button("Click Me").actionEvents()
        }
        subscription = buttonClicks.subscribe { println("Clicked!") }
    }

    override fun onUndock() {
        println("Unsubscribing!")
        subscription.unsubscribe()
    }
}
```

Everything works great. But one thing I'd like to undestand is when `onUndock()` is called. The `MyFragment` above called modally does not call `unUndock()` when I close it, and I don't get any `println()` notification of unsubscription. Does TornadoFX retain the instance? When does it actually dispose it?

**Comment by thomasnield** [comment] 2016-06-13 14:35
I think I might be unclear on the whole child/parent thing. I'm just trying to prevent memory leaks from RxJava. The whole `subscription.unsubscribe()` is critical because it does just that. If the source `buttonClicks`'s UI has fallen out of scope and no longer visible, everything related to that `MyFragment` instance should be GC'd I imagine. Unless... it is being retained for re-usability.

**Comment by edvin** [comment] 2016-06-13 14:40
I'm looking at this now, there is definitely some rough edges. If you just instantiate fragments, the ondock will not be called, and the listeners for onundock will not be called either. You have to use findFragment(MyFragment::class) to get around this. I've been trying to avoid this, will have another look at it.

Further more, when the modal closes, onUndock is not called either. Checking now.

**Comment by thomasnield** [comment] 2016-06-13 14:47
Okay glad I brought this up rather than maintained assumptions. I would imagine the `openModal()` should call `onUndock()`.

**Comment by edvin** [comment] 2016-06-13 14:55
OK, try the latest commit now. You can keep instantiating the fragment directly also :)

**Comment by edvin** [comment] 2016-06-13 14:56
`openModal` now attaches a listener to the `showing` property of the stage it creates and calls dock/undock accordingly. The other listeners do nothing when a modalStage is active.

**Comment by thomasnield** [comment] 2016-06-13 14:56
Let me know if I can help in any way.

**Comment by thomasnield** [comment] 2016-06-13 14:56
Okay awesome! Let me build it and give it a try...

**Comment by edvin** [comment] 2016-06-13 14:57
So glad you are documenting this, because it makes you look at it from a different angle and with different use cases so we find bugs more easily :)

**Comment by thomasnield** [comment] 2016-06-13 15:00
Yes, this iterative approach has been working out for both of us. Poking holes in something helps me learn it, making documentation easier after it is fixed.

I'll be in a meeting but Ill bring my tablet with me to verify it addresses the issue.

**Comment by thomasnield** [comment] 2016-06-13 16:53
Sorry been sidetracked. I'll verify this afternoon Texas time.

**Comment by edvin** [comment] 2016-06-13 17:03
No problem, great Thomas!

**Comment by thomasnield** [comment] 2016-06-13 23:55
Excellent. Just confirmed this worked. Are there any other cases we need to be accounted for in `onUndock()`? I can't think of any...

**Comment by edvin** [comment] 2016-06-14 06:52
No, just remember that it is possible that both `onDock` and `onUndock` can potentially be called multiple times during the life cycle of a View, if the View is used in different contexts.

**Comment by thomasnield** [comment] 2016-06-14 16:15
So maybe there needs to be a new abstract function such as `onDispose()`?

**Comment by thomasnield** [comment] 2016-06-14 16:16
Because it sounds like `onDock()` and `onUndock()` have to do with parent/child relationships, not necessarily disposal...

**Comment by edvin** [comment] 2016-06-14 16:28
Yes, but I don't know if there are any such hooks in JavaFX. Do any of you know?

**Comment by radicaled** [comment] 2016-06-14 16:35
> Yes, but I don't know if there are any such hooks in JavaFX. Do any of you know?

There are not, AFAIK. You can only rely on parent / scene going null.

**Comment by edvin** [comment] 2016-06-14 16:39
Thanks @radicaled. That's all I could find as well. But as long as you release resources in `onUndock` this should still work exactly as you need it to @thomasnield.

**Comment by thomasnield** [comment] 2016-06-14 16:58
Okay awesome. I am surprised there are no such hooks. But okay, at least it works. Hopefully complications arising from this will only be corner cases...
