### ISSUE TITLE
The Layout Debugger throws a bunch of errors if opened with `FX.reloadViewsOnFocus = true`

### ISSUE THREAD

**Issue by chinzen** [edvin/tornadofx#521] opened 2017-11-01 11:03 UTC
And those errors are not really informative.

**Comment by edvin** [comment] 2017-11-01 11:28
Thanks for reporting. It's supposed to ignore reload while the debugger is open, seems to be a regression. I'll look into it ASAP.

**Comment by edvin** [comment] 2017-11-06 08:19
I'm not able to reproduce, it works as it should for me. Can you create a small test case that shows the issue and add instructions describing what you do to provoke the error?

**Comment by chinzen** [comment] 2017-11-06 10:08
Ok.

MyApplication:
```kotlin
import tornadofx.*

class MyApplication : App(MainView::class) {
    init {
        reloadViewsOnFocus()
    }
}

class MainView : View() {
    override val root = borderpane {
        top {
            label("hi")
        }
    }
}
```

build.gradle:
```groovy
apply plugin: "kotlin"
apply plugin: "application"

buildscript {
    ext.kotlin_version = "1.1.51"

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

repositories {
    jcenter()
    mavenLocal()
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}

dependencies {
    compile "no.tornado:tornadofx:1.7.12-SNAPSHOT"
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:$kotlin_version"
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

I just run it from intellij (with the plugin) and press `Alt+Meta+J`.

**Comment by edvin** [comment] 2017-11-06 11:46
This is working as expected for me. Please try with version 1.7.12 and let me know if the problem persists :)

**Comment by chinzen** [comment] 2017-11-06 15:55
Well, that's curious. I was running `1.7.12-SNAPSHOT` from the posted `build.gradle`. Just in case I tried with `1.7.12` - the result is the same.

The errors are:
```
Nov 06, 2017 5:53:15 PM tornadofx.FX$Companion replaceComponent
INFO: Reloaded [Scene] MainView@5a3a2d7e
Nov 06, 2017 5:53:18 PM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
kotlin.UninitializedPropertyAccessException: lateinit property debuggingScene has not been initialized
	at tornadofx.LayoutDebugger.onDock(LayoutDebugger.kt:119)
	at tornadofx.UIComponent.callOnDock$tornadofx(Component.kt:572)
	at tornadofx.UIComponent$init$2.changed(Component.kt:464)
	at tornadofx.UIComponent$init$2.changed(Component.kt:296)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
	at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:831)
	at javafx.scene.Node.invalidatedScenes(Node.java:881)
	at javafx.scene.Node.setScenes(Node.java:919)
	at javafx.scene.Scene$9.invalidated(Scene.java:1119)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:111)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.Scene.setRoot(Scene.java:1072)
	at tornadofx.FX$Companion.replaceComponent(FX.kt:287)
	at tornadofx.NodesKt.reloadViews(Nodes.kt:143)
	at tornadofx.NodesKt$reloadViewsOnFocus$1.invoke(Nodes.kt:203)
	at tornadofx.NodesKt$reloadViewsOnFocus$1.invoke(Nodes.kt)
	at tornadofx.LibKt$onChange$$inlined$apply$lambda$2.changed(Lib.kt:238)
	at tornadofx.LibKt$onChange$$inlined$apply$lambda$2.changed(Lib.kt)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyBooleanWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:178)
	at javafx.beans.property.ReadOnlyBooleanWrapper$ReadOnlyPropertyImpl.access$100(ReadOnlyBooleanWrapper.java:148)
	at javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:144)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setFocused(Window.java:439)
	at com.sun.javafx.stage.WindowPeerListener.changedFocused(WindowPeerListener.java:59)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:97)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$275(GlassWindowEventHandler.java:150)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:148)
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1266)
	at com.sun.glass.ui.Window.notifyFocus(Window.java:1245)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

Nov 06, 2017 5:53:18 PM tornadofx.FX$Companion replaceComponent
INFO: Reloaded [Scene] tornadofx.LayoutDebugger@48861260
Nov 06, 2017 5:53:18 PM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
kotlin.KotlinNullPointerException
	at tornadofx.LayoutDebugger$onDock$1.run(LayoutDebugger.kt:116)
	at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by edvin** [comment] 2017-11-07 07:52
You seem to be running on Linux, maybe that's why it's behaving differently. Can you confirm which JDK you're running on? I'll try to set up a VM with the same configuration and see if I can trigger the bug that way. Looking at the code, there is no way onDock can be called without `debuggingScene` being assigned first, so this is indeed a mystery.

**Comment by chinzen** [comment] 2017-11-07 12:40
Ok, my JDK is `1.8.0_131`.

The full info:
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```
```
javafx.runtime.version=8.0.60
javafx.runtime.build=b00
```

**Comment by edvin** [comment] 2017-11-07 12:41
I think that's the issue - try with Oracle JDK :)

**Comment by jschneider** [comment] 2017-11-08 10:57
Works for me with Oracle JDK 8.
But I think it should run with OpenJDK, too...

**Comment by edvin** [comment] 2017-11-08 11:10
I'm not going to use resources on this now, as we're planning to port to Java 9, and OpenJDK will essentially be Oracle JDK for Java 9, so the problem will be fixed there. Further investigation will probably reveal a bug in OpenJDK 8, and the chances of having it fixed are slim to none IMO.

**Comment by jschneider** [comment] 2017-11-08 11:26
Fair enough.

**Comment by amasahara** [comment] 2019-08-13 06:45
> I just run it from intellij (with the plugin) and press Alt+Meta+J.

how to config it in intellij with meta key on windows

**Comment by edvin** [comment] 2019-08-13 07:01
Not sure I understand what you're asking @amasahara? There is nothing to configure, you just hit Alt+Meta+J.

**Closed** 2019-08-13 07:33 UTC
