### ISSUE TITLE
jdk10 / treeview not showing node markers

### ISSUE THREAD

**Issue by ronsmits** [edvin/tornadofx#1100] opened 2019-10-19 20:41 UTC
compiled keepassFX with tornadoFx 2.0.0-SNAPSHOT and oracle jdk11. Attached two screenshots showing the difference between 1.7.19 and 2.0.0-SNAPSHOT
![keepassfs-1 7 19](https://user-images.githubusercontent.com/595350/67151138-8675fc80-f2c1-11e9-85c9-00410672aeeb.png)
![keepass-2 0 0-SNAPSHOT](https://user-images.githubusercontent.com/595350/67151140-8970ed00-f2c1-11e9-8ee9-80ffa27cd648.png)

**Comment by edvin** [comment] 2019-10-19 21:40
Can you try to create a tree view in vanilla javafx with the same javafx version? It might be worth trying with JavaFX 13 as well to see if this is a bug that has already been fixed in JavaFX.

**Comment by ronsmits** [comment] 2019-10-19 23:03
running this code http://tutorials.jenkov.com/javafx/treeview.html with jdk 11 and jfx 11 the treeview works perfect
![Screenshot from 2019-10-20 01-03-29](https://user-images.githubusercontent.com/595350/67152408-79630880-f2d5-11e9-971d-5faef33dc5b0.png)

**Comment by edvin** [comment] 2019-10-21 08:20
Ok, how about a minimal runnable sample we can play with in TornadoFX?

**Comment by ronsmits** [comment] 2019-10-21 08:28
I whip something up tonight

**Comment by ronsmits** [comment] 2019-10-21 20:10
I created some very simple code. it can be found here https://github.com/tornadofx/jdk10treeviewsample

**Comment by edvin** [comment] 2019-10-24 18:55
It seems to be due to `cellFormat` overriding the `graphic` node or something like that. Looking at it now.

**Comment by edvin** [comment] 2019-10-24 18:59
I think this bug is also present in 1.0 master and is due to a recent cleanup. Will check what commit changed this.

**Comment by ronsmits** [comment] 2019-10-24 19:02
The 1.7.19 does it perfectly, as you can see in the example code I posted

**Comment by edvin** [comment] 2019-10-24 19:02
That doesn't contradict what I said :) 1.7.19 is not the same as current master :)

**Comment by edvin** [comment] 2019-10-24 19:03
It's due to `styleClass.clear()` in `TreeView.kt:cleanUp`

**Comment by edvin** [comment] 2019-10-24 19:12
We can't clear `styleClass` on `cleanUp()`, since a cell normally has the classes "cell", "indexed-cell" and "tree-cell". I've removed the `clear()` statement, but we could improve upon this by keeping the "native" classes and clearing the rest if needed.

**Comment by edvin** [comment] 2019-10-24 19:13
New snapshot pushed, and I've verified that your code sample works with jdk13 :)

**Comment by edvin** [comment] 2019-10-28 06:48
I'll close this since the issue is resolved.

**Closed by edvin** 2019-10-28 06:48 UTC
