### ISSUE TITLE
 I use find (View :: class) encountered a problem

### ISSUE THREAD

**Issue by jerlowliu** [edvin/tornadofx#557] opened 2017-12-01 11:00 UTC
I use find (View :: class) encountered a problem, I turned off the stage and then open, it will be incorrect. That pane already exists in other scenes.

`        val stage = Stage()
        stage.initOwner(FX.primaryStage)
        stage.initModality(Modality.APPLICATION_MODAL)
        val editView = find(ShopSettingEditView::class)

        stage.scene = Scene(editView.root)
        stage.title = "EditShop"
        stage.show()`

`Caused by: java.lang.IllegalArgumentException: Pane@6b193396[styleClass=root]is already set as root of another scene
	at javafx.scene.Scene$9.invalidated(Scene.java:1110)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:111)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.Scene.setRoot(Scene.java:1072)
	at javafx.scene.Scene.<init>(Scene.java:347)
	at javafx.scene.Scene.<init>(Scene.java:194)
	at com.soweil.view.system.company.ShopSettingView.edit(ShopSettingView.kt:69)
	... 66 more`

**Comment by nimakro** [comment] 2017-12-02 22:39
Hey @jerlowliu  well the problem is that you are using `View`'s the wrong way. 
TornadoFX handles `View`'s as singletons by default, so it can only be visible in one scene at the time.
Which is why you are getting an exception since your view is already visible in some other scene.
If you want to use `editView` in multiple dialogs you can either use `Fragment`'s since TornadoFX will always create a new Instance of it. Or you can use a new Scope for each `editView` like so: 

- View: ` find(ShopSettingEditView::class, Scope()).openModal()`

- Fragment: `find(ShopSettingEditFragment::class).openModal()`
Notice that I am calling `openModal` witch takes care of all the boilerplate code.

You can do some more reading about the concepts here:
- [Scopes](https://edvin.gitbooks.io/tornadofx-guide/content/part2/Scopes.html)

- [Fragment and OpenModal](https://edvin.gitbooks.io/tornadofx-guide/content/part1/3.%20Components.html)

**Comment by nimakro** [comment] 2017-12-03 09:12
I will close this issue since it is not a TornadoFX problem. If you have any further questions feel free to join out [slack](https://kotlinlang.slack.com/?redir=%2Fmessages%2Ftornadofx) channel

**Closed by nimakro** 2017-12-03 09:12 UTC
