### ISSUE TITLE
TextField Binding of Integer Property

### ISSUE THREAD

**Issue by gtnarg** [edvin/tornadofx#184] opened 2016-09-17 13:24 UTC
`textfield( model.myInt )`

where **model.myInt** is an Integer property is not supported whereas the following is:

```
  textfield(){
        bind( model.myInt )
   }
```

Is this by design or an oversight?

See full sample below.

Thanks
Grant

```

import javafx.beans.property.SimpleIntegerProperty
import tornadofx.*


class MyView : View("My View") {

    val model = MyPojoModel( MyPojo(1) )


    override val root = stackpane {

        // not supported
        // textfield( model.myInt )

        // works
        textfield(){
            bind( model.myInt )
        }

    }

    class MyPojo( var myInt: Int )

    class MyPojoModel(val mypojo: MyPojo) : ViewModel() {
        val myInt = bind { SimpleIntegerProperty(mypojo.myInt) }
    }

}
```

**Comment by edvin** [comment] 2016-09-17 13:42
It is by design, you must add IntegerStringConverter() as the second parameter. We might be able to support it though, I will check when I get back home tomorrow and let you know :)

**Comment by bekwam** [comment] 2016-09-17 17:34
Hi,

For the two-argument function, use NumberStringConverter.  javafx.beans.property.IntegerProperty is actually IntegerProperty<Number> rather than IntegerProperty<Integer>

        textfield(SimpleIntegerProperty(101), NumberStringConverter())

**Comment by edvin** [comment] 2016-09-17 17:41
Yeah, sorry, that's what I meant :) I'm on my phone in Oslo, just winging it :)

**Comment by edvin** [comment] 2016-09-18 16:00
This feature is now merged with master. Thanks @bekwam :)

**Closed by edvin** 2016-09-18 16:00 UTC
