### ISSUE TITLE
TornadoFX issue with java 13.0.2

### ISSUE THREAD

**Issue by halimpuckjava** [edvin/tornadofx#1186] opened 2020-03-17 10:15 UTC
hi

when try to execute tornadofx application

```
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$lau
```
java: 13.0.2,   openjfx: 13.0.2 ,  tornadofx 1.7.20

**Comment by edvin** [comment] 2020-03-17 10:21
Tornado 1 is for Java 8, TornadoFX 2 is for Java 9+. Try with the latest 2.0.0-SNAPSHOT from oss.sonatype.org. You might also want to try to run a vanilla Java based JavaFX sample first, to see that your JavaFX installation is complete. The error message might indicate otherwise.

**Comment by halimpuckjava** [comment] 2020-03-17 10:36
thanks for response

i will try what you suggest

**Comment by halimpuckjava** [comment] 2020-03-17 10:53
same error with 2.0.0-snapshot

**Comment by edvin** [comment] 2020-03-17 11:27
Create a vanilla JavaFX app, I believe you'll find that the issue is with your JavaFX installation, not TornadoFX :)

**Comment by ctadlock** [comment] 2020-04-07 06:58
Closing; not enough information, likely user issue.

**Closed by ctadlock** 2020-04-07 06:58 UTC
