### ISSUE TITLE
No ability to define custom CSS properties.

### ISSUE THREAD

**Issue by dant3** [edvin/tornadofx#203] opened 2016-11-03 13:17 UTC
JavaFX allows you to define custom css properties.
It would be nice if people could add their own typesafe css props for Stylesheet classes ad-hoc.

**Comment by t-boom** [comment] 2016-11-03 15:00
You can add typesafe properties ad-hoc. though the syntax is a little different. You set it with `prop.value = whatever` instead of `prop = whatever`. For example:

```kotlin
class MyApp : App(MyView::class, Styles::class) {
    class MyView : View("Custom CSS Properties Demo") {
        override val root = hbox {
            addClass(Styles.box)
        }
    }

    class Styles : Stylesheet() {
        companion object {
            val box by cssclass()
            val bg by cssproperty<MultiValue<Paint>>("-fx-background-color")
        }

        init {
            box {
                bg.value += Color.RED
                prefWidth = 500.px
                prefHeight = 300.px
            }
        }
    }
}
```

produces

![capture](https://cloud.githubusercontent.com/assets/1735659/19971194/f2f20eac-a1a3-11e6-8027-7adb2ff7451c.PNG)

---

(Note that you can't define properties for a specific class as not even the built in ones do that)

**Comment by t-boom** [comment] 2016-11-03 15:14
As far as your original question goes, can you point me to where `-fx-button-type` is documented? It's not in [the official CSS Reference](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html). Sadly, there seems to be a lot of CSS that isn't in there, so I'm still missing quite a bit.

**Comment by edvin** [comment] 2016-11-03 15:51
@thomasnield Do you know if creating custom properties is covered in the guide?

**Comment by dant3** [comment] 2016-11-03 16:04
I refer to the custom css properties rather then stock ones. You can add your own very custom CSS property handling to your views in JavaFX, but than you can't use them in typesafe manner in Stylesheet class.

**Comment by dant3** [comment] 2016-11-03 16:16
`cssproperty<ButtonType>("-fx-button-type")` almost did the trick. Now my problem is it lowercases value, which it shouldn't since it's a enum which is parsed by Java back.

**Comment by t-boom** [comment] 2016-11-03 16:21
Actually, I think your problem is the opposite. Lowercase enums work fine, but `ButtonType` isn't an enum. It's just a class with a bunch of `public static final ButtonType`s on it. It seems that, while we do support custom properties, we don't support rendering custom types. I'll have to dig into this more.

**Comment by t-boom** [comment] 2016-11-03 16:22
Or are you referring to a custom `ButtonType` enum? (I'm looking at `javafx.scene.control.ButtonType`)

**Comment by edvin** [comment] 2016-11-03 16:22
Maybe we could add an extension to the renderer so you can plug in a handler that returns true if it rendered the custom type for example?

**Comment by t-boom** [comment] 2016-11-03 16:23
@edvin That's a good idea

**Comment by dant3** [comment] 2016-11-03 16:24
No, ButtonType is a enum, defined in library as:
```
	public static enum ButtonType{FLAT, RAISED};
```

**Comment by t-boom** [comment] 2016-11-03 16:26
@dant3 Alright, sorry. I was looking at JavaFX's built in `ButtonType`. Currently, you can use the `unsafe` bypass (`unsafe("-fx-button-type", raw("FLAT"))`), though I'm not sure why the enum wasn't working. I'll look into it more. What library are you using?

**Comment by dant3** [comment] 2016-11-03 16:28
It's [JFoenix](https://github.com/jfoenixadmin/JFoenix)

**Comment by t-boom** [comment] 2016-11-03 16:50
I can confirm it is a case issue, which is both interesting and annoying. `unsafe("-fx-button-type", raw("RAISED"))` works just fine, but for some reason using `cssproperty<JFXButton.ButtonType>("-fx-button-type")` (which renders lowercase) does not.

This is annoying since all of JavaFX's internal enums are expected to be in snake case in CSS.

@edvin Do you think we need to add special support for all of JavaFX's internal enums, while other enums are rendered as-is?

**Comment by t-boom** [comment] 2016-11-03 16:56
```kotlin
class MyApp : App(MyView::class, Styles::class) {
    class MyView : View("Custom CSS Properties Demo") {
        override val root = stackpane {
            this += JFXButton("Test").apply {
                addClass(Styles.jbt)
                addClass("button-raised")
            }
        }
    }

    class Styles : Stylesheet() {
        companion object {
            val jbt by cssclass()
            val bt by cssproperty<JFXButton.ButtonType>("-fx-button-type")
        }

        init {
            root {
                prefWidth = 500.px
                prefHeight = 300.px
            }

            jbt {
                fontSize = 14.px
                backgroundColor += c(77, 102, 204)
                prefWidth = 200.px
                textFill = Color.WHITE
                bt.value = JFXButton.ButtonType.RAISED
            }
        }
    }
}
```

```css
.root {
    -fx-pref-width: 500px;
    -fx-pref-height: 300px;
}
.jbt {
    -fx-font-size: 14px;
    -fx-background-color: rgba(77, 102, 204, 1);
    -fx-pref-width: 200px;
    -fx-text-fill: rgba(255, 255, 255, 1);
    -fx-button-type: raised;
}
```

![capture](https://cloud.githubusercontent.com/assets/1735659/19976018/b02e3b30-a1b3-11e6-962f-a2223d0a4872.PNG)

```kotlin
class MyApp : App(MyView::class, Styles::class) {
    class MyView : View("Custom CSS Properties Demo") {
        override val root = stackpane {
            this += JFXButton("Test").apply {
                addClass(Styles.jbt)
                addClass("button-raised")
            }
        }
    }

    class Styles : Stylesheet() {
        companion object {
            val jbt by cssclass()
            val bt by cssproperty<JFXButton.ButtonType>("-fx-button-type")
        }

        init {
            root {
                prefWidth = 500.px
                prefHeight = 300.px
            }

            jbt {
                fontSize = 14.px
                backgroundColor += c(77, 102, 204)
                prefWidth = 200.px
                textFill = Color.WHITE
                unsafe("-fx-button-type", raw("RAISED"))
            }
        }
    }
}
```

```css
.root {
    -fx-pref-width: 500px;
    -fx-pref-height: 300px;
}
.jbt {
    -fx-font-size: 14px;
    -fx-background-color: rgba(77, 102, 204, 1);
    -fx-pref-width: 200px;
    -fx-text-fill: rgba(255, 255, 255, 1);
    -fx-button-type: RAISED;
}
```

![capture](https://cloud.githubusercontent.com/assets/1735659/19976056/dbdeedec-a1b3-11e6-95b2-80078a140dc7.PNG)

**Comment by dant3** [comment] 2016-11-10 16:57
Unfortunately javafx does not provides it's conversion code as a public API, so library authors left out on their own with this conversions. However there is no strict requirement on that.
IMO it would be nice to be able to supply custom value renderer, having javafx default behaviour as default value.

**Comment by t-boom** [comment] 2016-11-10 17:12
@dant3 Yes, it's been a thorn in my side for a while now. I still can't get dashed borders to work as they say they should.

That sounds reasonable. Hopefully I'll get time to implement custom renderers soon.

**Comment by t-boom** [comment] 2016-11-10 18:49
I've come up with a working method. `cssproperty<T>()` now also accepts a `(T) -> String` as a custom renderer. For example:

```kotlin
val renderedProp by cssproperty<String> { "${it.toUpperCase()}!!!" }

...

label {
    renderedProp.value = "bang"
}
```

Would be rendered as:

```css
.label {
    rendered-prop: BANG!!!;
}
```

**Comment by edvin** [comment] 2016-11-10 20:25
That looks fantastic, just what we need!

**Comment by edvin** [comment] 2016-11-14 10:26
Implemented, so I'll close this.

**Closed by edvin** 2016-11-14 10:26 UTC

**Comment by t-boom** [comment] 2016-11-14 15:46
@edvin This hasn't been merged into master yet. Did you want it in there, or did you want to wait till you can test it better?

**Comment by edvin** [comment] 2016-11-14 15:58
Ah, sorry. I think it would be fine to merge it. In the future I'd like to see if we can avoid the `.value=` assignment for custom properties, but this is in line with what we already have for now, so I think it's good to merge it.

**Comment by t-boom** [comment] 2016-11-14 16:01
The `.value=` isn't something I changed. That's what was already there for custom properties. As far as the API is concerned, the only change I made was the addition of the closure block to the `cssproperty` delegate.

**Comment by edvin** [comment] 2016-11-14 16:02
I know :) Will you merge and add a line to the changelog for this?

**Comment by t-boom** [comment] 2016-11-14 16:03
Will do

**Comment by edvin** [comment] 2016-11-14 16:20
Perfect!
