### ISSUE TITLE
Correction for "Manual validator" in "Validation with ViewModel" section.

### ISSUE THREAD

**Issue by hillol3786** [edvin/tornadofx#528] opened 2017-11-09 09:05 UTC
correction : **"validator"** instead of **"validate"**

Instead of using the built in required validator we can express the same thing manually:

`field("Name") {
    textfield(model.name).validator {
        if (it.isNullOrBlank()) error("The name field is required") else null
    }
}`

If you want to further customize the textfield, you might want to add another set of curly braces:

`field("Name") {
    textfield(model.name) {
        validator {
            if (it.isNullOrBlank()) error("The name field is required") else null
        }
    }
}`

**Comment by edvin** [comment] 2017-11-09 09:13
Not sure I see where the problem is. Where does it say validator instead of validate? PS: Issues against the guide should be opened in the guide project, or even better, via gitbooks, as it gives you a chance to quote the text containing the issue automatically.

**Comment by hillol3786** [comment] 2017-11-09 09:23
Ok, thanks for the suggestion. Actually I was following the wiki documentation. I see in gitbook it is correct but in wiki documentation it is still [incorrect](https://github.com/edvin/tornadofx/wiki/ViewModel).

**Comment by edvin** [comment] 2017-11-09 09:25
Aha! Thanks, I removed this page from the Wiki now :) We want to move all info to the guide and remove the wiki, just haven't had time yet :)

**Comment by hillol3786** [comment] 2017-11-09 09:27
Thanks.

**Comment by nimakro** [comment] 2017-12-03 09:21
@edvin I will close this since you fixed it?

**Closed by nimakro** 2017-12-03 09:21 UTC

**Comment by edvin** [comment] 2017-12-03 10:26
Thanks for picking up the slack, @nimakro :))
