### ISSUE TITLE
stop() function not called when application finishes

### ISSUE THREAD

**Issue by Ludtwigk** [edvin/tornadofx#955] opened 2019-03-22 07:35 UTC
I want to save data to a xml file when the application finishes. I've put my code inside the stop() function in the App class but nothing happens. Is there a way to put something in the closing event?

Thank you
Ludwig

**Comment by edvin** [comment] 2019-03-22 08:22
Overriding `stop` in your `App` class will work, provided the application is shut down normally. If it doesn't you might not have put it in the right place. It's also possible to explicitly register a shutdown hook. This example shows you how to do both:

```kotlin
class TestApp : App(TestView::class) {
    override fun start(stage: Stage) {
        super.start(stage)
        beforeShutdown {
            println("I'm a shutdown hook!")
        }
    }

    override fun stop() {
        println("Stopping")
    }
}
```

**Comment by Ludtwigk** [comment] 2019-03-22 08:29
What do you mean by shut down normally? Is there another way then closing it over the close(x button) in the top right corner of then window?
I've tried both methods you suggested but i didn't work for me.

Thanks for the fast reply!
Ludwig

**Comment by edvin** [comment] 2019-03-22 08:31
If the JVM crashes, there is no guarantee that any of these will be called, but both closing the last window and calling `Platform.exit()` will result in both of these callbacks being called. Please post a minimal sample application that showcases the issue. Also make sure you're running the latest version of Java 8.

**Comment by Ludtwigk** [comment] 2019-03-22 08:35
`class MainApp : App(ServerView::class){

    override fun start(stage: Stage) {
        super.start(stage)
        beforeShutdown {
            println("Shutdown")
            for(server in ServerStore.get())
                XmlHandler.writeToXML(server)
        }
    }

    override fun stop() {
        super.stop()
        for(server in ServerStore.get())
            XmlHandler.writeToXML(server)
    }

}`

This is my App class.
How can i call Platform.exit() and where? Is there a window closing event? I don't have a special button for closing i just have the the x button. 
Do you need other code snippets as well?

**Comment by edvin** [comment] 2019-03-22 08:41
That's not a runnable example, but I removed references to classes you didn't include and I can confirm that the callbacks are indeed called. You can call `Platform.exit()` from where ever you like if you want to exit the app, for example from a button click.

If you post a complete, runnable example, I'd be happy to check that as well. Try to set breakpoints both to confirm that the shutdown hook is registered, and that both callbacks are called. Timing issues might prevent console output when the app shuts down though.

**Comment by Ludtwigk** [comment] 2019-03-22 08:46
Okay so here is my ServerView class: 

`class MainApp : App(ServerView::class){

    override fun start(stage: Stage) {
        super.start(stage)
        beforeShutdown {
            println("Shutdown")
            for(server in ServerStore.get())
                XmlHandler.writeToXML(server)
        }
    }

    override fun stop() {
        super.stop()
        for(server in ServerStore.get())
            XmlHandler.writeToXML(server)
    }

}`

My Server class:

`package server

import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlRootElement

@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
class Server(@XmlElement val name: String, @XmlElement val address: String, @XmlElement val port: Int) {
    constructor() : this("No Name", "No Address", 0)
    init {
        ServerStore.add(this)
    }
}`

ServerStore class:

`package server

import javafx.collections.FXCollections
import jaxb.XmlHandler
import java.io.File
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlRootElement

@XmlRootElement
object ServerStore {

    @XmlElement
    private val serverList = FXCollections.observableArrayList<Server>()!!

    init {
        val file = File(Constants.pathToXML)
        file.createNewFile()
        if(!FileUtils.isEmpty(file))
            XmlHandler.readFromXML(file)
    }

    fun get() = serverList

    fun add(server: Server) {
        serverList.add(server)
    }

    fun find(serverName: String): Server?{
        for(server in serverList)
            if(server.name == serverName)
                return server

        return null
    }

    fun remove(serverName: String): Boolean {
        for(server in serverList)
            if(server.name == serverName){
                serverList.remove(server)

                return true
            }

        return false
    }
}`

and the XmlHandler class:

`package jaxb

import server.Server
import server.ServerStore
import java.io.File
import javax.xml.bind.JAXBContext
import javax.xml.bind.Marshaller

object XmlHandler {

    private val jaxbContext = JAXBContext.newInstance(Server::class.java)
    private val jaxbMarshaller = jaxbContext.createMarshaller()
    private val jaxbUnmarshaller = jaxbContext.createUnmarshaller()

    init {
        jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true)
    }

    fun writeToXML(server: Server){
        with(jaxbMarshaller){
            setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true)
            marshal(server, System.out)
            marshal(server, File(Constants.pathToXML))
        }
    }

    fun readFromXML(file : File) = (jaxbUnmarshaller.unmarshal(file)) as Server

    fun removeFromXML(server: Server) {

    }

}`

I hope that is enough code to test it.

**Comment by edvin** [comment] 2019-03-22 08:58
You didn't include `Constants` and `ServerView`. By the way, if you quote your code examples starting with three single ticks and the word kotlin on a separate line, you'll get syntax hl and other goodies :)

**Comment by Ludtwigk** [comment] 2019-03-22 09:01
ahh my bad sorry.
ServerView class:

'''
kotlin
package view

import controller.ServerController
import javafx.geometry.Orientation
import javafx.scene.control.ContentDisplay
import server.ServerStore
import tornadofx.*


class ServerView : View("Proxmox Horizon Client") {

    private val controller: ServerController by inject()

    init {
        importStylesheet("/css/bootstrap3.css")
    }

    override val root = vbox {
        prefWidth = 730.0
        prefHeight = 600.0


        hbox(spacing = 510) {
            paddingTop = 10
            paddingLeft = 20
            paddingRight = 20
            button("Add Server", imageview("icons/add24x24.png")) {
                prefHeight = 30.0
                action {
                    controller.openDialog()
                }
            }

            menubutton("", imageview("icons/info24x24.png")) {
                prefHeight = 25.0
                prefWidth = 60.0
                item("Settings").action { println("Opening Settings") }
                item("Info").action { println("Opening Info") }
            }
        }

        separator(Orientation.HORIZONTAL){
            spacing = 5.0
        }

        flowpane {
            paddingLeft = 20.0
            paddingRight = 20.0
            vgap = 20.0
            hgap = 20.0

            children.bind(ServerStore.get()) {
                button(it.name) {
                    imageview("icons/pve_logo100x80.jpg")
                    contentDisplay = ContentDisplay.TOP
                    wrapTextProperty().set(true)
                    setOnAction {
                        LoginView(this@button.text, this@ServerView).openWindow(resizable = false)
                    }
                    contextmenu {
                        item("Edit").action { controller.openEditDialog(it.name, it.address, it.port) }
                        item("Delete").action { ServerStore.remove(it.name) }

                    }
                }
            }

        }

        contextmenu{
            item("Add Server").action { controller.openDialog()}
        }


    }

}
'''

Constants class:

'''
kotlin
object Constants {

    const val pathToXML = "C:\\Temp\\test.xml"
}
'''

**Comment by edvin** [comment] 2019-03-22 09:07
I can confirm that the callbacks are indeed called using the latest version of Java 8 and the latest release of TornadoFX. If you are indeed sure the callbacks aren't called (verify by running in debug and setting breakpoints), you need to create a completely simple example app and gradually build in similar features to see which one might interfere, though I have a suspicion that this is just a misunderstanding :) Are you starting the app class or the view, for example?

**Comment by Ludtwigk** [comment] 2019-03-22 09:10
Im am running java version 1.8.0_201 and tornadofx version 1.7.18.
I am starting the app class. Is there another way?
Also thanks for your help and I'm loving your framework :)

**Comment by edvin** [comment] 2019-03-22 09:21
Versions should not be a problem then :) Yes, using the TornadoFX IDEA plugin you can also start Views and Fragments directly. If you did, the shutdown hooks in the app class wouldn't be registered, since running Views doesn't require an App class.

Did you confirm with debugging/breakpoints that your callbacks aren't registered? If so, please do as I suggested and reduce the complexity in your example. In fact, run this:

```kotlin
import javafx.application.Platform
import javafx.stage.Stage

class TestApp : App(TestView::class) {
    override fun start(stage: Stage) {
        super.start(stage)
        beforeShutdown {
            println("I'm a shutdown hook!")
        }
    }

    override fun stop() {
        println("Stopping")
    }
}

class TestView: View() {
    override val root = stackpane {
        button("Close").action {
            Platform.exit()
        }
    }
}
```

**Comment by Ludtwigk** [comment] 2019-03-22 09:26
Okay my bad. IntelliJ created a new Configuration file where the ServerView got launched and not the MainApp class..
I 've tried it now with the different Configuration and now its working.
Thank you!

**Closed** 2019-03-22 09:32 UTC
