### ISSUE TITLE
CSS url handler NOT picked up automatically

### ISSUE THREAD

**Issue by mgroth0** [edvin/tornadofx#470] opened 2017-09-29 03:21 UTC
I'm on tornadofx 1.7.11 and kotlin 1.1.51 and I always get this runtime warning:
```
INFO: Installing CSS url handler, since it was not picked up automatically
```
I know very little about css, but it feels like something is wrong because in CSS.kt,

```kotlin
  /**
         * Try to retrieve a type safe stylesheet, and force installation of url handler
         * if it's missing. This typically happens in environments with atypical class loaders.
         *
         * Under normal circumstances, the CSS handler that comes with TornadoFX should be picked
         * up by the JVM automatically.
         *
         * If an OSGi environment is detected, the TornadoFX OSGi Activator will install the OSGi
         * compatible URL handler instead.
         */
        private fun detectAndInstallUrlHandler() {
            try {
                URL("css://content:64")
            } catch (ex: MalformedURLException) {
                log.info("Installing CSS url handler, since it was not picked up automatically")
                try {
                    URL.setURLStreamHandlerFactory(Handler.HandlerFactory())
                } catch (installFailed: Throwable) {
                    log.log(Level.WARNING, "Unable to install CSS url handler, type safe stylesheets might not work", ex)
                }
            }
        }
    }
```

the comment says in normal environments it should work. I'm running on a mac from IntelliJ with Java 9, but I can't think of anything else that could be abnormal.

**Comment by edvin** [comment] 2017-09-29 05:34
Java 9 is not supporter yet. We’ll have a version for Java 9 ready within a few weeks.

**Comment by edvin** [comment] 2017-10-22 13:24
Closing this since it's working as intended for now. This will explicitly be adjuster for Java 9 though.

**Closed by edvin** 2017-10-22 13:24 UTC

**Comment by edvin** [comment] 2018-11-24 07:57
Not there yet. Feel free to help out on the jdk10 branch (targeting Java 11).
