### ISSUE TITLE
Classloader and resources access problem in Views inited by tornadofx

### ISSUE THREAD

**Issue by dant3** [edvin/tornadofx#209] opened 2016-11-10 16:33 UTC
This took me a while to figure out.

Given you have this simple code:

```
class MyApp : App(MyView::class) {
    init {
        println(javaClass.getResource("/test.txt");
    }
}

class MyView : View() {
    init {
        println(javaClass.getResource("/test.txt"); // prints null always. No matter if you use .classLoader or something else

            val thisClassLoader = javaClass.classLoader
            val thisParentClassLoader = thisClassLoader.parent // actually null, means we use root classloader here

            val appClassLoader = MyApp::class.java.classLoader
            val appParentClassLoader = appClassLoader.parent

            println("thisClassLoader == appClassLoader :" + (thisClassLoader == appClassLoader))
            println("appClassLoader == thisParentClassLoader :" + (appClassLoader == thisParentClassLoader))
            println("appParentClassLoader == thisParentClassLoader :" + (appParentClassLoader == thisParentClassLoader))
            println("appParentClassLoader == thisClassLoader :" + (appParentClassLoader == thisClassLoader))
    }
}
```

Running it you'll see this in console:

```
file:/path-to-your-build/test.txt
null
thisClassLoader == appClassLoader :false
appClassLoader == thisParentClassLoader :false
appParentClassLoader == thisParentClassLoader :false
appParentClassLoader == thisClassLoader :true
```

I can't load resources I need in init of main view of application due to this behaviour. I'm not exactly sure if this is issue with tornadofx or javafx, but never heard any complains on later about such behaviour.
I didn't found an easy way to create an instance of view to show in scene with `tornadofx.App` either - only overriding of `start(stage: Stage)` allows to do this, but the idea is creating view manually from App without supplying c-tor args to App makes loading resources work.

**Comment by edvin** [comment] 2016-11-10 17:29
TornadoFX has built in support for retrieving resources in a view, you can simply do:

```kotlin
println(resources["/test.txt"])
```

This will work for the primary view as well as any other view. Can you test this and see if it works for you?

**Comment by edvin** [comment] 2016-11-10 17:36
By the way, I ran your sample code as well (after adding a parenthesis instead of semicolon on the first line of init inside MyView) and it retrieves my test.txt no problem. If you still can't get this to work, can you create a small Maven based app, zip it up and attach here? I'm unable to reproduce any errors, everything works at it should for me.

**Comment by dant3** [comment] 2016-11-10 17:39
```
println(resources["/test.txt"])
```

This works, indeed. Not sure, why the code from my sample doesn't. I'll try to make a sample for you. Using gradle here, btw.

**Comment by edvin** [comment] 2016-11-10 17:53
Sweet. Anyway, this is the way to go :)

**Comment by edvin** [comment] 2016-11-15 13:34
I'll close this issue, since accessing resources works as expected.

**Closed by edvin** 2016-11-15 13:34 UTC
