### ISSUE TITLE
Plugin inject component not working for multimodule gradle project

### ISSUE THREAD

**Issue by vach** [edvin/tornadofx#138] opened 2016-07-07 08:58 UTC
When working in multimodule gradle project, plugin wont be able to find existing TFX components.

To reproduce check out [this](https://github.com/vach/jarvis/tree/tornado-bug) let intellij initialize the projects. Then go to view.kt file...

This might be related to [this intellij bug](https://youtrack.jetbrains.com/issue/KT-12498)

**Comment by edvin** [comment] 2016-07-07 09:03
Thank you. I can confirm the bug is with my implementation, I specifically do a shortcut in multi module projects. Will sort it out probably next week :)

**Comment by vach** [comment] 2016-07-07 09:05
Do you plan to opensource your plugin? I believe it will find some contributors as soon as this goes mainstream...

**Comment by edvin** [comment] 2016-07-07 09:06
It's already open sourced. I must say, I had no prior experience with writing IntelliJ plugins, and I did a lot of dirty tricks to get this working, mainly due to a lack of documentation, but there are absolutely big room for improvements. Check out the source code here:

https://github.com/edvin/tornadofx-idea-plugin

**Comment by vach** [comment] 2016-07-07 09:09
Oh that was my mistake, looked only popular repos.
P.S. i'll remove the branch when you close this issue.

**Comment by vach** [comment] 2016-07-07 09:18
Edvin is there a slack for this? I'd like to ask few minor things i stuck on...

**Comment by edvin** [comment] 2016-07-07 09:18
https://kotlinlang.slack.com/messages/tornadofx/

**Comment by edvin** [comment] 2016-07-23 16:28
This is now fixed in the just released version 1.5.2 of the plugin :)

**Closed by edvin** 2016-07-23 16:28 UTC
