### ISSUE TITLE
awaitUntil + TaskStatus

### ISSUE THREAD

**Issue by AlexP11223** [edvin/tornadofx#336] opened 2017-05-28 07:48 UTC
I tried to use `awaitUntil` to wait for result of async task in my test.

```
import javafx.beans.property.SimpleStringProperty
import org.junit.Test
import org.junit.runner.RunWith
import tornadofx.*
import kotlin.test.assertEquals
import de.saxsys.mvvmfx.testingutils.jfxrunner.*

@RunWith(JfxRunner::class)
class Test1 {
    @Test
    @TestInJfxThread
    fun doesSomething() {
        println(Thread.currentThread().name)

        val vm = MyViewModel()

        vm.loadStuff()

        vm.status.running.not().awaitUntil { it }

        assertEquals("hi", vm.stuff)
    }
}


class MyViewModel() : ViewModel() {
    val status = TaskStatus()

    val stuffProperty = SimpleStringProperty()
    var stuff: String by stuffProperty

    fun loadStuff() {
        runAsync(status) {
            Thread.sleep(1000)
            "hi"
        } ui {
            println(it)
            stuff = it
        }
    }
}
```

```
        <dependency>
            <groupId>de.saxsys</groupId>
            <artifactId>mvvmfx-testing-utils</artifactId>
            <version>1.6.0</version>
        </dependency>
```

Output:

```
JavaFX Application Thread

java.lang.AssertionError: 
Expected :hi
Actual   :null
```

After debugging I found out that the problem is with `status` check.

On first check of `if (condition(value)) {` both old and new values are true (from manual call, `changeListener.changed(this, value, value)` https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/FX.kt#L640 ).

If I replace it with something like this it works fine:

```
    runLater(100.millis) {
        changeListener.changed(this, value, value)
    }
```

I think alternative workaround would be to add something like `completed` property to TaskStatus.

**Comment by edvin** [comment] 2017-05-28 09:00
OK, I added the `completed` to `TaskStatus`. Does that hook work better?

**Comment by AlexP11223** [comment] 2017-05-28 16:58
Seems to work kind of backwards... Maybe something related to synchronization/concurrency?

```
import javafx.beans.property.SimpleStringProperty
import tornadofx.*

class MMainView : View("MMain") {
    override val root = borderpane {
    }

    override fun onDock() {
        MyViewModel().loadStuff()
    }
}

class MyViewModel() : ViewModel() {
    val status = TaskStatus()

    val stuffProperty = SimpleStringProperty()
    var stuff: String by stuffProperty

    init {
        status.completed.onChange {
            println("completed $it")
        }
        status.running.onChange {
            println("running $it")
        }
    }

    fun loadStuff() {
        runAsync(status) {
            Thread.sleep(1000)
            "hi"
        } ui {
            println(it)
            stuff = it
        }
    }
}

class MApp : App(MMainView::class)
```

```
running true
completed true
running false
hi
completed false
```

**Comment by edvin** [comment] 2017-05-28 18:07
Actually, I think it is working as designed (sort of).

It's running, then completed, then it's no longer running. Check. Then your output appears, because it's no longer running when `ui` gets control. The last `completed false` is probably because the TaskStatus object is disconnected from the task. Since it's reusable, it needs to be able to reset. For this use case it's working against us though, let me have a look at it and see what I can come up with.

**Comment by edvin** [comment] 2017-05-28 18:11
Yeah, the reason is that the task is disconnected from the tast status when it's completed:

```kotlin
        if (status?.item == this)
            status.item = null
```

When I think about it, it might be wrong to disconnect it upon task completion though. I will try to remove that code and run some tests.

**Comment by AlexP11223** [comment] 2017-05-28 18:17
Yeah, but I think that's only part of the issue. `done` is not running from FX thread, unlike other state functions.
That's probably why `completed` is true before `running` false.

Probably should set it like this:

```
    override fun succeeded() {
        (completedProperty as BooleanProperty).value = true
    }

    override fun failed() {
        (completedProperty as BooleanProperty).value = true
    }

    override fun cancelled() {
        (completedProperty as BooleanProperty).value = true
    }
```

**Comment by AlexP11223** [comment] 2017-05-28 18:24
Actually if I am not missing anything, I think disconnection is not a problem for my case. `awaitUntil` should still see it in correct order if it is set from FX thread.

```
<-- start await
running true
running false
hello
completed true <-- await finished, ok
completed false <-- doesn't care
```

**Comment by edvin** [comment] 2017-05-28 18:33
I'm not sure you should write code where that matters, but I do agree it might be conceived as more correct, so I've changed it :) Thank you for your thorough investigation of this issue, this was very helpful.

**Comment by edvin** [comment] 2017-05-28 18:37
My last comment cross posted with yours, so this is a comment for your previous one :)

Yeah that's right, but for cases where you create a specific TaskStatus instance it will look weird that the state changes back to completed=false. The actual task you connected to the TaskStatus object is infact still completed. If you reuse the TaskStatus object however, it would change to completed = false when it is reassigned.

Hopefully this change will create less confusion, so I think we'll stick with it unless you have any objections? :)

**Comment by AlexP11223** [comment] 2017-05-28 19:55
I use it for tests, as shown in the first message.

Yeah, I think this behavior is more correct.

~~hm, but now it may be less convenient for me, because as understand I would need to reset it before running task again, otherwise await will fail similarly as before with `running`. (that is I need to create a new `TaskStatus` instance... and probably make it a property, for bindings. I hope JavaFX bindings can handle it?)~~

Actually no, looks like `completed` is set much earlier than `running`, before exited the synchronous part of `runAsync`. So it should be fine, thank you :)

Submitted PR with test app.

**Comment by edvin** [comment] 2017-05-28 20:11
Thank you. Good work!

**Closed** 2017-05-28 20:12 UTC
