### ISSUE TITLE
Known good project / gradle setup with Intellij 2019.2 Runtime 11

### ISSUE THREAD

**Issue by ppslim** [edvin/tornadofx#1064] opened 2019-08-30 15:03 UTC
I have having difficulty trying to use TordnadoFX with Intellij 2019.2 Community (using Snap to obtain) which is now using Runtime 11.

I have had partial success on Windows (using toolbox), but not on Linux (with Snap). I am also unsure if the problems may be linked to Kotlin 1.3.50 being migrated in (which is not in play on Windows).

I cannot seen to manually progress a project in Intellij and use TordnadoFX. This is with or without the TFX IntelliJ plugin as well.

The docs are sparse on setup detail, or cover rather older versions of Kotlin & IntelliJ. Are there any new instructions that may be preventing my progress?

**Comment by edvin** [comment] 2019-09-02 07:07
What version on Java is used to run IntelliJ is not relevant. You need to obtain OpenJDK8 and OpenJFX for Java 8 and run your app against that. There is nothing else to it really :)

**Comment by ppslim** [comment] 2019-09-02 08:44
Good point. I had noted that requirement but forgot to list it.

I have untold issues using OpenJDK on Ubuntu with OpenJFX. In short, I couldn't get them working with a JavaFX HelloWorld, let alone along side TornadoFX.

This was all prior to the Runtime 11 switch (which was an automatic thing via Snap, not a requested action).

Due to this, I have Oracle JDK 1.8u131 in play just for my account and this is setup as a custom JDK.

This was perfectly functional until recently. I cannot pin it on a Snap upgrade or to Runtime 11, but this is one of the limited set of items I can recall has changed in any way.

I had Kotlin 1.3.21 when it was working fine when raising #997 and was using the IntelliJ TFX plugin at that point. At some point this moved to 1.3.40, but don't recall trying to create any new projects (existing ones worked), now with 1.3.50 I can't even run older projects (I cannot 100% pin older projects failing on current IDE setup, as I had been playing about with the event bus to explore alternates solutions to my #997 issue).

I suspect some of the issue is more in the TornadoFX plugin for IntelliJ, as it continuously tells me it has detected the TornadoFX framework and offers to configure, over and over, even though I have done this (and this does occur on older projects that used to work normally).

There is some reality, that I do not know the first place to start on diagnosing what the issue is, be this Gradle, IntelliJ itself or the TornadoFX plugin.

**Comment by maimari** [comment] 2019-10-05 06:58
Hello.
Thank you for the great framework and plug-ins.
Thank you, Evin. Thank you for your dedication.
I'm learning Cotlin now, so I don't know much,
Write down my experience.
the present 
Windows 10
intelij 2019.2.3 
java 13 + javafx 13 sdk & jmod (installed in different folders)
kotlin 1.3.5
vm option 
--module-path "javafx-sdk installation path/lib"
--add-modules=javafx.controls,javafx.fxml
Executing tonadofx example in is good

But there's a Java compatibility problem with the gradle.
If the gradle version is officially released, java11
Snapshot enabled us to java13.

**Comment by ppslim** [comment] 2019-11-26 13:17
Been meaning to come back to this.

I did not locate an absolute definitive list of causes, as I have not run into exactly the same issues every time. As my project work moved on, I am unsure I have been in a position to see all of them occur.

However, the majority of issues are linked to the TornadoFX Intellij plugin defaults, rather than TornadoFX itself.

I cannot locate the reference item that directed me to it, but IntelliJ will only work with Gradle 5 and above. Gradle version being the most primary issue I faced whilst trying to work with TFX. This would also confirm my initial thought that projects that used to work, stopped working, after an Intellij update that prompted the minimum version reqs.

After updating my projects gradle properties wrapper to use gradle 5.2, TFX now works reasonably well. I have not had chance to look at newer versions of gradle, to avoid rocking my boat too much.

Either way, the plugin is setup to use gradle 4.4. Bumping this and Kotlin to 1.3.50 resolves this, but as of right now, the plugin cannot create TornadoFX projects "right first time"

**Comment by maimari** [comment] 2019-11-27 07:11
Hello.
I am sorry but I'm not good at English.
I hope you understand.

I did understand tornadofx plugin gradle problem.
I did fix problem for tornadofx plugin gradle part.
I do attaching some files.

While the outstanding Edvin leader officially modified plugin.
Perhaps you can use it as a temporary fix.

1. Unzip the downloaded file once
2. Just replace the original jar file in the tfx plugin folder.

The original source is not fixed.
Fixing the template file
Sorry. I'm not good at understanding the source

Modified the Gradle file to version 5.2.
Added build.gradle file for javafx and tornadofx.
And temporarily changed some settings.

Thank you dir edvin.
Have a good day ^^!

[tornadofx-idea-plugin-1.7.17.2.zip](https://github.com/edvin/tornadofx/files/3895469/tornadofx-idea-plugin-1.7.17.2.zip)

**Comment by ctadlock** [comment] 2020-04-28 08:09
Not sure what the issue is here. The latest versions all work fine together. Closing, can reopen with more details

**Closed by ctadlock** 2020-04-28 08:09 UTC
